Secure boot working with debian and alpine kernels and debian root. Done for this weekend.

diff --git a/recovery/sbin/setup-initos b/recovery/sbin/setup-initos
--- a/recovery/sbin/setup-initos
+++ b/recovery/sbin/setup-initos
@@ -51,11 +51,14 @@ linux_alpine() {
   KERNEL_VERSION=$(cat /usr/share/kernel/lts/kernel.release)
 
   # This is the version that will be used in the UKI (can be changed)
-  echo $KERNEL_VERSION > /boot/version
+  # echo $KERNEL_VERSION > /boot/version
 
   # Versioned name, matching the modules dir.
   mv /boot/vmlinuz-lts /boot/vmlinuz-${KERNEL_VERSION}
-  ln -s /boot/vmlinuz-${VKERNEL_VERSION}  /boot/vmlinuz
+  ln -s /boot/vmlinuz-${KERNEL_VERSION}  /boot/vmlinuz
+
+  # Decompress all zst files.
+  (cd /lib/firmware; find . -name "*.zst" -exec zstd -d --rm -f {} \;  || true) 2>/dev/null
 }
 
 # vlinux_alpine gets the virtual kernel, creates a squash with the modules.
@@ -72,11 +75,11 @@ vlinux_alpine() {
   mkdir -p ${WORK}/virt
   vinit $VKERNEL_VERSION
   if [ ! -f $WORK/virt/modloop-${VKERNEL_VERSION}.sqfs ]; then
-    mksquashfs /lib/modules/${VKERNEL_VERSION} $WORK/virt/modloop-${VKERNEL_VERSION}.sqfs
+    mksquashfs /lib/modules/${VKERNEL_VERSION} /boot/modules-${VKERNEL_VERSION}.sqfs
   fi
 }
 
-# vinit updates the initramfs for the virt kernel, in case init script is changed.
+# vinit updates the initramfs for the virt kernel
 vinit() {
   VKERNEL_VERSION=$(cat /boot/version-virt)
   # -k - keep the file
@@ -84,7 +87,10 @@ vinit() {
 
   rm -rf ${WORK}/virt/initfs
   mkdir -p ${WORK}/virt/initfs
-  mkinitfs -k -t ${WORK}/virt/initfs  -i /sbin/init-vm -F "base btrfs squashfs virtio initos" -o ${WORK}/virt/initramfs-$VKERNEL_VERSION $VKERNEL_VERSION
+
+  mkinitfs -k -t ${WORK}/virt/initfs  -i /sbin/init-vm \
+     -F "base btrfs squashfs virtio initos" \
+     -o /boot/initramfs-$VKERNEL_VERSION $VKERNEL_VERSION
 }
 
 # Generate an unsigned efi image, based on alpine with a custom init script.
@@ -108,27 +114,24 @@ efi() {
   # exist.
   EFI_FILE=${EFI_FILE:-/boot/efi/EFI/BOOT/Initos-NEW.EFI}
 
-  KERNEL_VERSION=$(cat /boot/version)
-  [ -z ${KERNEL_VERSION} ] && echo "Missing kernel config" && return
+  for KERNEL_VERSION in $(ls /lib/modules) ; do
+    KERNEL=/boot/vmlinuz-${KERNEL_VERSION}
+    [ ! -f ${KERNEL} ] && echo "Missing kernel ${KERNEL}" && return
 
-  KERNEL=/boot/vmlinuz-${KERNEL_VERSION}
-  [ ! -f ${KERNEL} ] && echo "Missing kernel ${KERNEL}" && return
+    [ ! -f /lib/modules/${KERNEL_VERSION}/modules.dep ] && echo "Missing modules" && return
 
-  [ ! -f /lib/modules/${KERNEL_VERSION}/modules.dep ] && echo "Missing modules" && return
+    local img=/boot/initrd-initos.img-${KERNEL_VERSION}
 
-  local img=/boot/initrd-initos.img-${KERNEL_VERSION}
+    build_initrd ${KERNEL_VERSION} ${img}
 
-  build_initrd ${KERNEL_VERSION} ${img}
+    echo "loglevel=6 console=ttyS0 console=tty1 net.ifnames=0 panic=5 debug_init iomem=relaxed" > /boot/cmdline
 
-  echo "loglevel=6 console=ttyS0 console=tty1 net.ifnames=0 panic=5 debug_init iomem=relaxed" > /boot/cmdline
-
-  mkdir -p /boot/efi/EFI/BOOT
-  efi-mkuki \
-    -c /boot/cmdline \
-    -o ${EFI_FILE} \
-      ${KERNEL} /boot/intel-ucode.img /boot/amd-ucode.img ${img}
-
-  echo ${KERNEL_VERSION} > /boot/efi/version
+    mkdir -p /boot/efi/EFI/BOOT
+    efi-mkuki \
+      -c /boot/cmdline \
+      -o ${EFI_FILE} \
+        ${KERNEL} /boot/intel-ucode.img /boot/amd-ucode.img ${img}
+  done
 }
 
 build_initrd() {
@@ -165,10 +168,6 @@ build_initrd() {
 # The initramfs is different - the additional file will disable shell and trigger verification.
 sign() {
   set -e
-  local KERNEL_VERSION=$(cat /boot/version)
-
-  # Need to rebuild the initrd - for some reason the hash is not found.
-
   # Alpine expects keys on /etc/uefi-keys/{db.crt,db.key}
   if [ ! -f /etc/uefi-keys/db.crt ]; then
     sign_init
@@ -177,36 +176,12 @@ sign() {
       openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -out /etc/uefi-keys/root.key
       openssl ec -in /etc/uefi-keys/root.key -pubout -out /etc/uefi-keys/root.pem
       ssh-keygen -y -f /etc/uefi-keys/root.key > /etc/uefi-keys/authorized_keys
-    fi
-    cp /etc/uefi-keys/root.pem /boot/efi/EFI
-    cp /etc/uefi-keys/root.pem /boot/
-
-  KERNEL=/boot/vmlinuz-${KERNEL_VERSION}
+  fi
+  cp /etc/uefi-keys/root.pem /boot/efi/EFI/
+  cp /etc/uefi-keys/root.pem /boot/
 
   # The hash must be on the signed initrd - not on the efi disk (which is mounted)
   cp /boot/efi/hash* /boot/
-  (find /boot/hash* /boot/root.pem | sort | cpio --quiet --renumber-inodes -o -H newc | gzip) > /boot/initos-hashes.cpio.gz
-
-  # TODO: add authorized_keys and root.pem
-
-  echo "loglevel=0 quiet console=ttyS0 console=tty1 net.ifnames=0 panic=5 rdinit=/sbin/init-secure initos.secure" > /boot/cmdline.secure
-
-  efi-mkuki \
-    -c /boot/cmdline.secure \
-    -o /boot/efi/EFI/BOOT/tmp-${KERNEL_VERSION}.EFI \
-      ${KERNEL} \
-       /boot/intel-ucode.img /boot/amd-ucode.img \
-       /boot/initrd-initos.img-${KERNEL_VERSION} /boot/initos-hashes.cpio.gz
-
-   #    ${WORK}/initos-secure.cpio.gz
-
-  sbsign --cert /etc/uefi-keys/db.crt --key /etc/uefi-keys/db.key \
-    --output /boot/efi/EFI/BOOT/BOOTX64.EFI \
-    /boot/efi/EFI/BOOT/tmp-${KERNEL_VERSION}.EFI
-  echo ${KERNEL_VERSION} > /boot/efi/EFI/BOOT/BOOTX64.version
-  echo ${KERNEL_VERSION} > /boot/efi/EFI/BOOT/BOOTX64.${KERNEL_VERSION}
-  rm /boot/efi/EFI/BOOT/tmp-${KERNEL_VERSION}.EFI
-
   cp /etc/uefi-keys/*`.auth` /boot/efi/EFI
   cp /etc/uefi-keys/*`crt` /boot/efi/EFI
   cp /etc/uefi-keys/*`cer` /boot/efi/EFI
@@ -216,8 +191,51 @@ sign() {
   chmod 755 /boot/efi/EFI/*.crt
   chmod 755 /boot/efi/EFI/*.cer
 
-  rm /.dockerenv
-  # TODO: also sign the squash and modules
+
+  (find /boot/hash* /boot/root.pem \
+   | sort \
+   | cpio --quiet --renumber-inodes -o -H newc \
+   | gzip) > /boot/initos-hashes.cpio.gz
+
+  # TODO: add authorized_keys and root.pem
+
+  echo "loglevel=0 quiet console=ttyS0 console=tty1 net.ifnames=0 panic=5 rdinit=/sbin/init-secure initos.secure" > /boot/cmdline.secure
+
+  # for each initrd
+  for k in $(ls /boot/vmlinuz-*) ; do
+    KERNEL_VERSION=${k##*vmlinuz-}
+    KERNEL=/boot/vmlinuz-${KERNEL_VERSION}
+
+    efi-mkuki \
+      -c /boot/cmdline.secure \
+      -o /boot/efi/EFI/BOOT/tmp-${KERNEL_VERSION}.EFI \
+        ${KERNEL} \
+        /boot/intel-ucode.img /boot/amd-ucode.img \
+        /boot/initrd-initos.img-${KERNEL_VERSION} /boot/initos-hashes.cpio.gz
+
+    sbsign --cert /etc/uefi-keys/db.crt --key /etc/uefi-keys/db.key \
+      --output /boot/efi/EFI/BOOT/InitOS-Signed-${KERNEL_VERSION}.EFI \
+      /boot/efi/EFI/BOOT/tmp-${KERNEL_VERSION}.EFI
+
+    rm /boot/efi/EFI/BOOT/tmp-${KERNEL_VERSION}.EFI
+    echo $KERNEL_VERSION
+  done
+
+  # local KERNEL_VERSION=$(cat /boot/version)
+  # KERNEL=/boot/vmlinuz-${KERNEL_VERSION}
+
+  # efi-mkuki \
+  #   -c /boot/cmdline.secure \
+  #   -o /boot/efi/EFI/BOOT/tmp-${KERNEL_VERSION}.EFI \
+  #     ${KERNEL} \
+  #      /boot/intel-ucode.img /boot/amd-ucode.img \
+  #      /boot/initrd-initos.img-${KERNEL_VERSION} /boot/initos-hashes.cpio.gz
+
+  # sbsign --cert /etc/uefi-keys/db.crt --key /etc/uefi-keys/db.key \
+  #   --output /boot/efi/EFI/BOOT/BOOTX64.EFI \
+  #   /boot/efi/EFI/BOOT/tmp-${KERNEL_VERSION}.EFI
+
+  # rm /boot/efi/EFI/BOOT/tmp-${KERNEL_VERSION}.EFI
 }
 
 
@@ -240,11 +258,15 @@ efi2() {
 
 }
 
+mods_sqfs() {
+  for version in $(ls /lib/modules) ; do
+    mod_sqfs $version
+  done
+}
 
 sqfs() {
-  version=${1:-$(cat /boot/version)}
   firmware_sqfs
-  mod_sqfs $version
+  mods_sqfs
 }
 
 # firmware_sqfs builds /boot/efi/firmware.sqfs using /x/initos/firmware or /lib/firmware
