Finally got NVidia to work reliably. In the process decided to simplify again - while initializing NVidia using Debian kernel and Alpine rootfs works, it is too complicated and fragile and to use it the versions and 'user' space need to be kept in sync, etc.
So back to original idea of Debian based rootfs, with minimal systemd use and Alpine as a sidecar
handling networking and updates. Instead of switching root 2x, it goes directly from Initrd to the
read-only signed debian.

Keeping the Alpine-based rootfs around for now, but may move it to an example dir

diff --git a/rootfs/sbin/initos b/rootfs/sbin/initos
--- a/rootfs/sbin/initos
+++ b/rootfs/sbin/initos
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 export PATH="$PATH:/usr/bin:/bin:/usr/sbin:/sbin"
 
@@ -34,7 +34,6 @@ load_drivers() {
   # read -t 4 -n 1 key
 
   # export MODE=$key
-
 
   udevadm settle
 
@@ -82,22 +81,19 @@ move_mounted_to_sysroot() {
 # Info log - shown on console, logged.
 logi() {
 	last_emsg=""$@""
-	echo "INITOS: $last_emsg..." > /dev/kmsg
-	echo "$last_emsg\n"
+	echo "INITOS: $last_emsg" > /dev/kmsg
+	echo "INITOS: $last_emsg"
 }
 
 lfatal() {
   echo "FAILED: "$@""
   edump
 
-  if [ "${KOPT_initos}" != "USB" ]; then
-    echo "Rebooting in 20 sec"
-    blkid
-    
-    sleep 20
-    reboot -f
-  fi
-  busybox ash
+  echo "Rebooting in 20 sec"
+  blkid
+  
+  sleep 20
+  reboot -f
 }
 
 # dump info to the EFI partition (which exists if we managed to get the
@@ -110,13 +106,13 @@ lfatal() {
 #
 # All 'fatal' logs go to /boot/efi if it is mounted.
 edump() {
-  local dst=${1:-/z/initos/log/${MAC}}
-
-  if [ ! -e /z/initos ]; then
-    echo "Boot disk not found"
-    return
+  if [ -d /x/initos ]; then 
+    dst=/x/initos/log
+  else 
+    dst=/boot/efi/log
   fi
-
+  mkdir -p $dst
+  
   # current date and time
   export LOG_DIR=${dst}/$(date +"%Y-%m-%d-%H-%M-%S")
   mkdir -p ${LOG_DIR}
@@ -135,30 +131,33 @@ edump() {
   env > ${LOG_DIR}/env.log
 }
 
-# open LUKS using TPM2.
-# TODO: attempt to open all LUKS devices (multiple NVMEs)
-# Mointing the /x and rootfs after, btrfs may span multiple 
-# disks.
-open_luks() {
-  local crypted=$1
+# With the KEY from TPM or user input, open any disk that is locked with that key.
+# The disks will use luks-1... IDs - and are expected to have a single multi-disk
+# btrfs root filesystem.
+open_disks() {
+  local KEY=$1
+  # Real blkid - not the busybox one which lacks '-t'
+  # TODO: use a PARTLABEL
+  parts=$(blkid -t TYPE=crypto_LUKS -o device )
   
-  echo "Found LUKS device: ${cryptd}"
-  
-  unlock_tpm $cryptd
-  if [ $? -eq 0 ]; then
-    logi "TPM unlocked ${cryptd}"
-    return 0
-  fi
-
-  return 1
+  local cnt=1
+  echo "$parts" | while read -r part; do 
+    echo -n "$KEY" | cryptsetup open $part luks-${cnt} -
+    if [ $? -eq 0 ]; then
+      logi "Opened $part"
+      cnt=$((cnt + 1))
+    else 
+      echo "Attempt to unlock $part failed"
+    fi
+  done
 }
 
 mount_btrfs_raw() {
-  local root_device=${1}
-  local dst=${2}
+  local root_device=${1:-/dev/mapper/luks-1}
+  local dst=${2:-/x}
 
-  BTRFS_OPTS="-o nobarrier"
-  #  -o compress
+  BTRFS_OPTS=" -o noatime -o nodiratime"
+  #  -o compress -o nobarrier 
 
   mkdir -p ${dst}
 
@@ -173,13 +172,13 @@ mount_btrfs_raw() {
 # Persistent disk mounted on /x
 # Mount /sysroot from the BTRFS subvolume, mount additional volumes.
 mount_sysroot() {
-  root_device=/dev/mapper/c
+  # This is the first LUKS device open
+  root_device=/dev/mapper/luks-1
   x=/x
 
   if [ -f ${x}/swap ]; then
     swapon ${x}/swap
   fi
-
 
   if [ -z $INITOS_ROOT ]; then
     if [ -d "${x}/@" ]; then
@@ -191,6 +190,8 @@ mount_sysroot() {
 
   mkdir -p /sysroot
   if [ -d ${x}/${INITOS_ROOT} ]; then
+    logi "USING /x/$INITOS_ROOT as 'main' OS"
+
     mount -t btrfs "${root_device}" /sysroot -o subvol=${INITOS_ROOT} \
       -o noatime -o nodiratime
     if [ $? -ne 0 ]; then
@@ -211,6 +212,11 @@ mount_sysroot() {
   if [ -d ${x}/initos/etc ] ; then
     cp -a ${x}/initos/etc /etc
   fi
+
+  if [ -d ${x}/initos/root ] ; then
+    mount -o bind ${x}/initos/root /root
+  fi
+
 }
 
 upstamp() {
@@ -238,25 +244,54 @@ start_os() {
   if [ ! -d /sysroot/etc ]; then
     logi "INITOS_ROOT not set, running as primary - additional OS as VMs/pods"
     run_standalone
+    # TPM will sleep, insecure will have a shell
+    return
   fi
+
+  logi "INITOS_ROOT set and mounted, prepare to switch_root and restart as InitOS sidecar"
+
+  ver=$(uname -r)
+  # if [ ! -d /sysroot/lib/modules/$ver ]; then 
+  #    # should also be done at install time - but kernel may change.
+  #    # Nvidia drivers need to be re-installed on the main OS
+  #    cp -a /lib/modules/${ver} /sysroot/lib/modules
+  #    touch /sysroot/lib/modules/${ver}/FROM_EFI
+  # fi
+  
+  # Don't forget to clean /etc/machine-id, systemd, etc before switching
+  set -x 
+  # The EFI may push updates. 
+  cp /sbin/setup-initos* /sysroot/sbin
+  cp /sbin/initos* /sysroot/sbin
+  mkdir -p /sysroot/var/initos # Local files and boot next
+  cp -a /var/initos /sysroot/var/
+
+  # This works if the debian includes the kernel modules (copy above)
+  # commented out for now to test the sqfs modules
+  # umount /lib/modules/${ver}
+  # # May need to do it 
+  # mount -o bind /x/${INITOS_ROOT}/usr/lib/modules/${ver} /lib/modules/${ver}
+  set +x
+
   # requires rc-local systemd service, since systemd kills all processes
   # This will run 'sidecar', which starts initos in a chroot.
   #cp /etc/rc.local ${rootfs}/etc
 
   if [ -f /sysroot/init ]; then
     logi "Preparing to switch root $INITOS_ROOT - custom init"
-    initos move_mounted_to_sysroot
+    move_mounted_to_sysroot
     exec switch_root /sysroot /init
   elif [ -f /sysroot/lib/systemd/systemd ]; then
     logi "Preparing to switch root $INITOS_ROOT (systemd)"
-    initos move_mounted_to_sysroot
+    move_mounted_to_sysroot
     exec switch_root /sysroot /usr/bin/systemd --system 
     #  systemd --log-level=err --unit=rescue.target --system --default-standard-output=tty --default-standard-error=tty
   elif [ -f /sysroot/sbin/init ]; then
     logi "Preparing to switch root $INITOS_ROOT"
-    initos move_mounted_to_sysroot
+    move_mounted_to_sysroot
     exec switch_root /sysroot /sbin/init
   fi
+
   lfatal "Failed to switch root"
 }
 
@@ -274,8 +309,15 @@ run_standalone_start() {
     cp -a /var/initos/local/etc/* /etc
   fi
 
+  if [ -d /x/initos/root ]; then
+    mount -o bind /x/initos/root /root 
+  fi
   mkdir -p /root/.ssh
-  cp /var/initos/local/authorized_keys /root/.ssh/authorized_keys
+  if [ ! -f /root/.ssh/authorized_keys ]; then
+    # Allow local override (to add more keys usually). This is for 
+    # the 'sidecar' OS.
+    cp /var/initos/local/authorized_keys /root/.ssh/authorized_keys
+  fi
 
   # The encrypted disk is trusted.
   if [ -d /x/initos/etc ]; then
@@ -296,6 +338,9 @@ run_standalone_start() {
     echo "nameserver 1.1.1.1" > /etc/resolv.conf
   fi
 
+  # Otherwise screen saver doesn't unlock... PAM
+  chmod u+s /usr/sbin/unix_chkpwd
+ 
   # Not using init - openrc (like s5) is just a launcher for 
   # initialization scripts.
   /sbin/openrc sysinit
@@ -310,11 +355,23 @@ run_standalone_start() {
   # Show the interfaces
   ifconfig -a
   cat /etc/ssh/*.pub 
+
+  if [ -f /x/initos/start ]; then 
+    # This can start VMs/docker images/etc
+    # Remember: this is insecure, unprotected - no secrets or 
+    # important stuff. Anyone who has access to the machine can
+    # do whatever they want and read everything - just like any
+    # unencrypted machine, regardless of OS.
+    sh -x /x/initos/start
+  fi
+
 }
 
 run_standalone() {
   run_standalone_start
+}
 
+startui() {
    # TODO: may execute some startup from /x
   if [ -f /etc/init.d/seatd ]; then
     addgroup build seat
@@ -330,22 +387,14 @@ run_standalone() {
   chown build $XDG_RUNTIME_DIR
   export HOME=/home/build
 
-  if [ -f /x/initos/start ]; then 
-    # This can start VMs/docker images/etc
-    # Remember: this is insecure, unprotected - no secrets or 
-    # important stuff. Anyone who has access to the machine can
-    # do whatever they want and read everything - just like any
-    # unencrypted machine, regardless of OS.
-    source /x/initos/start
-  fi
 
   # TODO: loop showing the interface in secure mode, maybe with
   # a small shell to read a set of commands.
 
   # DEBUG ONLY
-  #su - build -c 'labwc -s foot'
+  su - build -c 'labwc -s foot' &
 
-  sh
+  #sh
     # Takes care of zombies
   exec tini -s sleep -- infinity 
 }
@@ -397,6 +446,11 @@ mesh_init() {
   iw phy phy0 interface add p2p0 type p2p-device
   ip link set p2p0 up
   wpa_cli -i p2p0 p2p_find p2p_connect p2p_group_add
+}
+
+common() {
+  # common initos functions
+  touch /tmp/initos_common
 }
 
 # TODO: check lbu (for USB-only OS, can be encrypted)
diff --git a/rootfs/sbin/initos-initrd b/rootfs/sbin/initos-initrd
--- a/rootfs/sbin/initos-initrd
+++ b/rootfs/sbin/initos-initrd
@@ -78,7 +78,10 @@ boot_initos() {
   cp /sbin/initos* /sbin/setup-initos* /sysroot/sbin/
   rm -f /sysroot/.dockerenv
 
-  
+  if [ -d /local/modprobe.d ]; then
+    cp -a /local/modprobe.d /sysroot/etc
+  fi
+
   # Expect a TPM file containing the handle to be present, otherwise use manual unlock.
   # In both cases a LUKS partition is required - it must be set in insecure mode or 
   # while creating the hard disk image.
@@ -93,6 +96,7 @@ boot_initos() {
    move_mounted_to_sysroot
    exec switch_root /sysroot /sbin/initos-init-manual
   fi
+  # TODO: update the scripts for debian (may use bash on the main rootfs)
   lfatal "Failed to switch root"
 }
 
@@ -219,6 +223,7 @@ mount_initos() {
   mount_overlay initos /initos/rootfs
 
   kernel_ver=$(uname -r)
+ 
   mkdir -p /lib/firmware
   mkdir -p /lib/modules/${kernel_ver}
   mount -o bind /initos/rootfs/lib/firmware /lib/firmware
@@ -253,6 +258,8 @@ mount_overlay() {
   if [ $? -ne 0 ]; then
      lfatal "Error: Failed to mount overlay ${name}"
   fi
+
+
 }
 
 # All remaining mounted dirs will be moved under same dir in /sysroot,
@@ -275,23 +282,22 @@ move_mounted_to_sysroot() {
 # Info log - shown on console, logged.
 logi() {
 	last_emsg=""$@""
-	echo "INITOS: $last_emsg" > /dev/kmsg
-	echo "$last_emsg"
+	echo "INITOSRD: $last_emsg" > /dev/kmsg
+	echo "INITOSRD: $last_emsg"
 }
 
 lfatal() {
   echo "FAILED: "$@""
   local save=/boot/efi/log
   mkdir -p $save
-  if [ -d $save ]; then
-    blkid > $save/blkid.log
-    dmesg > $save/dmesg.log
-    cat /proc/filesystems > $save/filesystems
-    cat /proc/devices > $save/devices
-    lsmod > $save/lsmod.log
-  fi
 
-  echo "Rebooting in 20 sec"
+  blkid > $save/blkid.log
+  dmesg > $save/dmesg.log
+  cat /proc/filesystems > $save/filesystems
+  cat /proc/devices > $save/devices
+  lsmod > $save/lsmod.log
+
+  echo "Rebooting in 20 sec. Block devices:"
 
   # TODO: if /boot/efi is mounted, save to the EFI partition
   blkid
@@ -362,20 +368,33 @@ find_boot() {
   local hashf=${4:-$(cat /local/initos.hash)}
 
   # findfs doesn't work well if multiple partitions with same label are present.
+  # This just waits for the expected label to show up, will try all of them
   retry 4 findfs LABEL=$first >/dev/null 2>&1
-
-  # Find all block devices of type EFI
-  # Doesn't seem to work with TYPE=EFI type, vfat is ok
-  # Using EFI UUID -t UUID=DE32-BBB1 doesn't work on alpine blkid...
-  #efi_devices1=$(blkid | grep 'TYPE="vfat"' | cut -d: -f1)
 
   local temp_mount_point=/boot/efi
   
-  # for kind in /dev/nvme /dev/mmc /dev/sd ;  do 
+  for diskt in /dev/nvme /dev/mmc /dev/sd ;  do 
+    device=$(blkid | grep "LABEL=\"$first\"" | cut -d: -f1 | grep $diskt)
+    echo "$device" | while read -r d; do 
+      if [ -z "$d" ]; then
+        continue
+      fi
+      logi "Attemptint to open $d using $vname"
+      try_disk "$d" "$hashf" "$mountp" "$vname"
+      if [ $? -eq 0 ]; then
+        export BOOT_LABEL=$first
+        break
+      fi
+    done
+    if [ -e /dev/mapper/$vname ]; then
+      return 0
+    fi
+  done
 
   for kind in $first BOOTA BOOTB ;  do
     # This selects only one if the label is used on multiple disk. 
     #device=$(findfs LABEL=$kind)
+    # This is busybox blkid, lacks '-l'
     device=$(blkid | grep "LABEL=\"$kind\"" | cut -d: -f1)
     echo "Looking for signed bootstrap on $kind $device"
     if [ -z "$device" ]; then
@@ -384,6 +403,7 @@ find_boot() {
     echo "$device" | while read -r d; do 
       try_disk "$d" "$hashf" "$mountp" "$vname"
       if [ $? -eq 0 ]; then
+        export BOOT_LABEL=$kind
         break
       fi
     done
@@ -391,6 +411,10 @@ find_boot() {
       return 0
     fi
   done
+
+  echo "XXXX TEMPORARY DEBUG - INITRD FAILED, check efi partitions"
+  sh
+
   return 2
 }
 
diff --git a/rootfs/sbin/setup-builder b/rootfs/sbin/setup-builder
--- a/rootfs/sbin/setup-builder
+++ b/rootfs/sbin/setup-builder
@@ -65,6 +65,9 @@ export REPO=${REPO:-git.h.webinf.info/costin}
 # For the docker build variant.
 export DOCKER_BUILDKIT=1
 
+
+TAG=${TAG:-v250410}
+
 set -e
 
 
@@ -95,8 +98,10 @@ all() {
 
 clean() {
   buildah rm initos-base initos kernel >/dev/null 2>&1  || true
+  buildah rmi ${REPO}/kernel:latest >/dev/null 2>&1  || true
   buildah rmi ${REPO}/initos-base:latest >/dev/null 2>&1  || true
   buildah rmi ${REPO}/initos:latest  >/dev/null 2>&1 || true
+  buildah rmi initos initios-base kernel  >/dev/null 2>&1 || true
   # rmi -a # all images
   rm -rf ${WORK}
 }
@@ -119,19 +124,49 @@ _build_cmd() {
   local POD=$2
   shift; shift
 
-  # Cache directories - deb and alpine
-  mkdir -p ${WORK}/apkcache ${WORK}/lib_cache
-  VOLS="$VOLS -v ${WORK}/lib_cache:/var/lib/cache"
-  VOLS="$VOLS -v ${WORK}/apkcache:/etc/apk/cache"
-
   buildah rm ${POD} || true
 
   buildah pull ${BASE}
+
+  # Cache directories - deb and alpine
+  mkdir -p ${WORK}/apkcache ${WORK}/lib_cache ${WORK}/apt
+  VOLS="$VOLS -v ${WORK}/lib_cache:/var/lib/cache"
+  VOLS="$VOLS -v ${WORK}/apkcache:/etc/apk/cache"
+  VOLS="$VOLS -v ${WORK}/apt:/var/cache/apt/archives"
+
+  VOLS="$VOLS -v ${WORK}:/data"
+
   buildah --name ${POD} ${VOLS} from ${BASE}
+
   buildah copy ${POD} rootfs/sbin /sbin
+  buildah copy ${POD} rootfs/bin /bin
+  buildah copy ${POD} rootfs/etc /etc
+
   buildah run ${POD} -- "$@"
 
+  echo "Commiting as ${REPO}/${POD}:${TAG}"
+  buildah commit ${POD} ${REPO}/${POD}:${TAG}
   buildah commit ${POD} ${POD}
+}
+
+_run_cmd() {
+  local POD=$1
+  shift
+
+  # Cache directories - deb and alpine
+  mkdir -p ${WORK}/apkcache ${WORK}/lib_cache ${WORK}/apt
+  VOLS="$VOLS -v ${WORK}/lib_cache:/var/lib/cache"
+  VOLS="$VOLS -v ${WORK}/apkcache:/etc/apk/cache"
+  VOLS="$VOLS -v ${WORK}/apt:/var/cache/apt/archives"
+
+  VOLS="$VOLS -v ${WORK}:/data"
+
+  buildah copy ${POD} rootfs/sbin /sbin
+  buildah copy ${POD} rootfs/bin /bin
+  buildah copy ${POD} rootfs/etc /etc
+
+  buildah run ${VOLS} ${POD} -- "$@"
+
 }
 
 # Only the kernel and drivers (no nvidia - install on the partition)
@@ -140,34 +175,53 @@ debkernel() {
   _build_cmd debian:bookworm-slim kernel /sbin/setup-initos add_deb_kernel
 }
 
-debui() {
-  _build_cmd debian:bookworm-slim kernel /sbin/setup-deb ui
-}
-
+# Use the initos-base image to copy $1 image to $2 local dir.
+# Alternative to 'crane export' - without remote push.
 exportfs() {
   buildah --name orig from $1
   buildah run \ 
      -v $2:/data
      --mount=type=bind,from=orig,src=/,dst=/mnt \
-    initios -- cp -a /mnt/ /data
+    initios-base -- cp -a /mnt/ /data
   buidah rm orig
 }
 
-# Clean build using initos image
+efi() {
+  initos_efi_builder "$@"
+}
+
+# Using the base image and the kenel, build a container that
+# adds a layer containing the initrd and sqfs files.
+# 
+# This can also be generated on a cache dir - and used for 
+# signing.
 initos_efi_builder() {
-  local POD=initos
+  local POD=${POD:-initos}
+
+
+  # if ! buildah images | grep -q "${REPO}/initos-base:${TAG}"; then
+  #   echo "Image ${REPO}/initos-base:${TAG} not found locally. Pulling from repository..."
+  #   buildah pull ${REPO}/initos-base:${TAG}
+  #   buildah tag ${REPO}/initos-base:${TAG} initos-base
+  # fi
+  set -x 
 
   buildah rm ${POD} || true
-  buildah --name ${POD} from initos-base 
-  # ${REPO}/initos-base:latest
- 
-  initos_efi_update 
+  KIMG=kernel # ${REPO}/kernel:${TAG}
 
-  buildah commit ${POD} ${REPO}/initos-efi-builder:latest
+ buildah --name ${POD} from initos-base
+ 
+  # This could be done in the container with debootstrap
+  buildah copy --from ${KIMG} ${POD} /boot/ /boot/
+
+  initos_efi_update "$@"
+
+  buildah commit ${POD} ${REPO}/initos-efi-builder:${TAG}
+  buildah commit ${POD} ${POD}
 }
 
 initos_efi_add() {
-  local POD=initos
+  local POD=${POD:-initos}
 
   buildah copy ${POD} rootfs/sbin /sbin
   buildah copy ${POD} rootfs/bin /bin
@@ -180,35 +234,70 @@ initos_efi_add() {
 
 }
 
-initos_efi_update() {
-  local POD=initos
+update() {
+  initos_efi_update "$@"
+}
 
+updatesqfs() {
+  local POD=${POD:-initos}
+  echo "Updating SQFS for ${POD}"
+  
   buildah copy ${POD} rootfs/sbin /sbin
   buildah copy ${POD} rootfs/bin /bin
-  buildah copy --chown build ${POD} rootfs/home /home
+  #buildah copy --chown build ${POD} rootfs/home /home
   buildah copy ${POD} rootfs/etc /etc
 
-  # This could be done in the container with debootstrap
-  buildah copy --from kernel ${POD} /boot/ /boot/
+  MOUNTS="-v ${WORK}/lib/modules:/lib/modules \
+  -v ${WORK}/lib/firmware:/lib/firmware \
+  -v ${WORK}/boot:/boot"
+  MOUNTS="$MOUNTS -v ${WORK}:/data"
+
+  buildah run ${MOUNTS} \
+    ${POD} --  setup-initos vinit
+
+  buildah run ${MOUNTS} \
+     ${POD} -- setup-initos sqfs /data/efi/initos
+
+  buildah run ${MOUNTS} \
+    ${POD}  setup-initos build_initrd
+
+}
+
+# Use the existing 'initos' (or $POD) container to update the sqfs.
+# Will not commit it - can be used locally
+# 
+# The pod can be updated with more packages, after changes 'update' must
+# be called
+# 
+initos_efi_update() {
+  local POD=${POD:-initos}
+  local DEST=${1:-/boot}
+
+  echo "Updating ${POD} sqfs "
+  buildah copy ${POD} rootfs/sbin /sbin
+  buildah copy ${POD} rootfs/bin /bin
+  #buildah copy --chown build ${POD} rootfs/home /home
+  buildah copy ${POD} rootfs/etc /etc
+
 
   # Build roimage and verity signature, directly on the out img dir.
   #
   # Will create SQFS files for the EFI images - smaller than including
   # the files directly and easier to use.
+  KIMG=kernel # ${REPO}/kernel:${TAG}
 
-  buildah run \
-    --mount=type=bind,from=kernel,src=/lib/modules,dst=/lib/modules \
-    --mount=type=bind,from=kernel,src=/lib/firmware,dst=/lib/firmware \
-    ${POD} -- setup-initos vinit
+  MOUNTS="--mount=type=bind,from=${KIMG},src=/lib/modules,dst=/lib/modules \
+    --mount=type=bind,from=${KIMG},src=/lib/firmware,dst=/lib/firmware"
 
-  buildah run \
-    --mount=type=bind,from=kernel,src=/lib/modules,dst=/lib/modules \
-    --mount=type=bind,from=kernel,src=/lib/firmware,dst=/lib/firmware \
-    ${POD} -- setup-initos recovery_sqfs recovery /boot
+  MOUNTS="$MOUNTS -v ${WORK}:/data"
 
-  buildah run \
-    --mount=type=bind,from=kernel,src=/lib/modules,dst=/lib/modules \
-    --mount=type=bind,from=kernel,src=/lib/firmware,dst=/lib/firmware \
+  buildah run ${MOUNTS} \
+    ${POD} --  setup-initos vinit
+
+  # buildah run ${MOUNTS} \
+  #    ${POD} -- setup-initos sqfs ${DEST}
+
+  buildah run ${MOUNTS} \
     ${POD}  setup-initos build_initrd
 
 }
@@ -216,6 +305,8 @@ initos_efi_update() {
 # It still needs an initrd.
 # The image needs to be saved as a .img or sqfs.
 virt() {
+  POD=${POD:-initos}
+
   VER=$(ls /lib/modules | grep cloud | tail)
   # Virt files. 
   VIRT=${VIRT:-${WORK}/vimg}
@@ -228,13 +319,13 @@ virt() {
     cp /boot/vmlinuz-$VER ${VIRT}/vmlinuz
   fi
   # Build the initrd used by sign
-  buildah copy initos rootfs/sbin /sbin
+  buildah copy ${POD} rootfs/sbin /sbin
 
   buildah run -t \
     -v ${VIRT}:/opt/virt \
     --mount=type=bind,src=/lib/modules,dst=/lib/modules \
     --mount=type=bind,src=/lib/firmware,dst=/lib/firmware \
-      initos -- \
+      ${POD} -- \
     setup-initos vinit $VER
 
   # May want to add the modules from the host image (for virt), but seems
@@ -243,11 +334,13 @@ virt() {
 
 # will create the images from the running containers.
 commit() {
-  # About 500MB
-  buildah push ${REPO}/initos:latest
-  
   # About 200MB
-  buildah push ${REPO}/initos-base:latest
+  buildah push ${REPO}/initos-base:${TAG}
+
+  buildah push ${REPO}/kernel:${TAG}
+
+  # About 500MB
+  buildah push ${REPO}/initos:${TAG}  
 }
 
 ##### Dockerfile
diff --git a/rootfs/sbin/setup-initos-host b/rootfs/sbin/setup-initos-host
--- a/rootfs/sbin/setup-initos-host
+++ b/rootfs/sbin/setup-initos-host
@@ -52,7 +52,7 @@ scrub() {
 # This should be called explicitly by the user - it will normally not be done automatically.
 # In practice we need ~100M on the EFI, and some btrfs volume.
 #
-wipe_disk() {
+install_wipe_disk() {
   DISK=${1:-/dev/nvme0n1}
 
   # if disk contains 'nvme', add 'p'
@@ -77,25 +77,46 @@ wipe_disk() {
   # 512M would fit - but painful, better to have some
   # space.
   # a single partition is hard to manage.
-  parted "$DISK" mkpart primary fat32 0 1024
+  parted "$DISK" mkpart primary fat32 1 2048
   parted "$DISK" set 1 boot on
   parted "$DISK" set 1 esp on
   parted "$DISK" name 1 "BOOTA"
 
-  parted "$DISK" mkpart primary fat32 1024 2048
+  parted "$DISK" mkpart primary fat32 2048 4096
   parted "$DISK" name 2 "BOOTB"
   parted "$DISK" set 2 esp on
   
   # Create the LUKS partition
-  parted "$DISK" mkpart primary ext4 2048 -1
-  parted "$DISK" name 3 "LUKS"
+  parted "$DISK" mkpart primary ext4 4096 100%
+  parted "$DISK" name 3 "INITOSLUKS"
 
   partprobe $DISK
 
   bootd ${DISK}${suffix}1 BOOTA
   bootd ${DISK}${suffix}2 BOOTB
 
-  addEFI ${DISK}
+  #install_boot_options ${DISK}
+}
+
+install_wipe_usb() {
+  DISK=${1:-/dev/sda}
+
+  parted --script --machine -- "${DISK}" mklabel gpt
+
+  parted "$DISK" mkpart primary fat32 1 4096
+  parted "$DISK" set 1 boot on
+  parted "$DISK" set 1 esp on
+  parted "$DISK" name 1 "BOOTUSB"
+  
+  # Create the LUKS partition
+  parted "$DISK" mkpart primary ext4 4096 100%
+  parted "$DISK" name 2 "INITOSLUKSUSB"
+
+  partprobe $DISK
+
+  bootd ${DISK}1 BOOTUSB
+
+  #install_boot_options ${DISK}
 }
 
 # Initialize the boot partition - make filesystem, copy the 
@@ -110,9 +131,13 @@ bootd() {
   cp -a /boot/efi/* /mnt/$LABEL
 }
 
+boot() {
+  install_boot_options "$@"
+}
+
 # This must be called after changing the partition tables.
 # 
-addEFI() {
+install_boot_options() {
   d=${1:-/dev/nvme0n1}
   efibootmgr -B -b 1001
   efibootmgr -B -b 1002
@@ -126,11 +151,11 @@ addEFI() {
   #     -u 'console=ttyS0 rdinit=/sbin/initos-initrd console=tty1 net.ifnames=0 panic=5 initos=USB loglevel=6 debug iomem=relaxed' \
   #     -L "InitOS InsecureB" -l "\initosA.EFI"
 
-  efibootmgr -c -d ${d} -p 2 \
+  efibootmgr -c -d ${d} -p 1 \
       -b 1003 \
       -L "InitOS InSecureA" -l "\EFI\BOOT\BOOTx64.EFI"
 
-  efibootmgr -c -d ${d} -p 1 \
+  efibootmgr -c -d ${d} -p 2 \
       -b 1004 \
       -L "InitOS InSecureB" -l "\EFI\BOOT\BOOTx64.EFI"
 
@@ -163,16 +188,45 @@ bootNext() {
   reboot -f
 }
 
+# Run before the upgrade - mounts the 'next' EFI partition, 
+# remove old files if the SQFS has changed (small disk, rsync doesn't work
+# very well)
 upgrade_start() {
-  mkdir -p /boot/b
+  local newh=${1}
+  local clabel=${2}
+
+  # Created by InitRD based on the label it used for the current boot.
+  # If it used BOOTA - BOOT_NEXT will be B
   local next=$(cat /var/initos/BOOT_NEXT)
+  local label=BOOT${next:-B}
 
-  echo "Mounting BOOT{$next} to /boot/b and accepting new version"
+  if [ "$clabel" != "" ]; then 
+    label=$clabel
+  fi
 
-  mount LABEL=BOOT${next:-B} /boot/b
+  mkdir -p /boot/b
+  mount LABEL=$label /boot/b
+  if [ $? -ne 0 ]; then
+    echo "Failed to mount $label to /boot/b"
+    return 1
+  fi
+
+  local eh=$(cat /boot/b/initos/initos.hash )
+
+  if [ "$eh" = "$newh" ]; then
+    echo "Mounting $label to /boot/b - same SQFS $newh"
+  else
+    echo "Mounting $label to /boot/b and accepting new version $newh existing $eh"
+    ###### XXX After all are upgraded rm -f /boot/b/initos/initos.*
+  fi
 }
 
-upgrade_finish() {
+# Finish the upgrade. Optional 'reboot' CLI to restart, otherwise on next
+# boot the new image will be used.
+# 
+# After the new image is healthy, a 'swapNext' needs to be called to make 
+# it default.
+upgrade_end() {
   umount /boot/b
 
   rm  /sys/firmware/efi/efivars/dump-*
@@ -190,7 +244,19 @@ upgrade_finish() {
   fi
 
   sync
-  reboot -f &
+  if [ "$1" = "reboot" ]; then 
+    /sbin/setup-initos-host upgrade_reboot &
+    echo "Rebooting in 5 seconds"
+  fi
+
+  return 0
+}
+
+upgrade_reboot() {
+  sync
+  sleep 5
+  reboot -f
+  
 }
 
 # swapNext is useful for switching A and B as first. 
@@ -227,21 +293,31 @@ mkLUKS() {
 
 mkbtrfs() {
   local MAPPER=${1:-c}
+  local DPATH=${2:-/x}
 
   mkfs.btrfs /dev/mapper/${MAPPER}
   # Doesn't really matter, visible after encyption unlock.
-  btrfs filesystem label /dev/mapper/${MAPPER} "ROOT"
+  btrfs filesystem label /dev/mapper/${MAPPER} "INITOSROOT"
 
-  mount /dev/mapper/${MAPPER} /x
+  mount /dev/mapper/${MAPPER} ${DPATH}
 }
 
 addbtrfs() {
-  local MAPPER=${1:-c1}
-  btrfs device add /dev/mapper/${MAPPER} /x
+  local MAPPER=${1:-luks-2}
+  local DPATH=${2:-/x}
+
+  btrfs device add /dev/mapper/${MAPPER} ${DPATH}
 
 }
 
+# Initialize the /x BTRFS disk with expected volumes and files
 xinit() {
+  mksubvol
+
+
+}
+
+mksubvol() {
     btrfs subvol create /x/vol
     btrfs subvol create /x/@home
     btrfs subvol create /x/@cache
@@ -518,7 +594,5 @@ find_mac() {
   MAC=${MAC//:/-}
 
 }
-
-
 
 "$@"
